name: CI
on: 
    push: 
        branches: ["**"]
    pull_request:
        branches: [main]
jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            
            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: '8.0.x'
                
            - name: Restore
              run: dotnet restore Insights.sln
                
            - name: Build
              run: dotnet build Insights.sln --no-restore --configuration Release
                
            - name: Unit Tests
              run: dotnet test Insights.Tests.Unit --no-build --configuration Release
                
            - name: Integration Tests
              run: dotnet test Insights.Tests.Integration --no-build --configuration Release